% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Question 3},
  pdfauthor={Tapiwa Nyamupachitu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Question 3}
\author{Tapiwa Nyamupachitu}
\date{2025-11-19}

\begin{document}
\maketitle

Loading the data

\subsubsection{Momentum : Introduction}\label{momentum-introduction}

In this section, I assess the effectiveness of momentum as an investment
signal over the past decade. I defined momentum as cumulative returns
over the last 12 months. As a result, I used a 12-month return signal
(excluding the most recent month), and evaluated whether momentum has
demonstrated predictive power. Additionally, I also checked whether a
local long-only equity fund has systematically tilted toward
high-momentum stocks

\subsection{Information Coefficient
(IC)}\label{information-coefficient-ic}

To start, I calculated the Information Coefficient, measured as the
Spearman rank correlation between the momentum signal and future 3-month
returns. The IC series gives us insight into how consistently momentum
has predcited returns over time.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 3) Visualise IC over time}
\NormalTok{ic\_data }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ ic)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"steelblue"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
        \AttributeTok{title =} \StringTok{"Information Coefficient Over Time"}\NormalTok{,}
        \AttributeTok{y =} \StringTok{"Spearman Rank Correlation"}\NormalTok{,}
        \AttributeTok{x =} \StringTok{"Date"}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Question-3_files/figure-latex/unnamed-chunk-3-1.pdf}}

Overall, we see that the IC remains positive across most months, albiet
with some noise. This suggests a modest but consistent positive
relationship between past returns and future peformance. This is
consistent with academic findings on momentum.

\subsection{Signal Decay}\label{signal-decay}

Next I investigated how the signal's predictive power changes over time.
This involved measuring the Spearman correlation between current
momentum and future momentum swings.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 3) Plot the decay}
\FunctionTok{ggplot}\NormalTok{(decay\_by\_month, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ decay)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"darkgreen"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Signal Decay Over Time"}\NormalTok{,}
         \AttributeTok{x =} \StringTok{"Date"}\NormalTok{,}
         \AttributeTok{y =} \StringTok{"Avg Spearman Correlation with Future Momentum"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Question-3_files/figure-latex/unnamed-chunk-5-1.pdf}}

The decay profile shows that the signal retains strong persistence
across several months, indicating that stocks with high momentum tend to
stay ranked highly for a reasonable period. This supports its use as a
predictive signal.

\subsection{Quintile Performance}\label{quintile-performance}

I sorted the stocks into quintiles based on their momentum each month,
forming a long-short strategy (Q1-Q5). This allows us to quantify the
return spread between high and low momentum portfolios.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Summary stats over full sample}
\NormalTok{ls\_summary }\OtherTok{\textless{}{-}}\NormalTok{ ls\_perf }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}
        \AttributeTok{mean\_ls =} \FunctionTok{mean}\NormalTok{(long\_short, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{median\_ls =} \FunctionTok{median}\NormalTok{(long\_short, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{hit\_rate =} \FunctionTok{mean}\NormalTok{(long\_short }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{    )}

\NormalTok{ls\_summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##    mean_ls median_ls hit_rate
##      <dbl>     <dbl>    <dbl>
## 1 0.000842  0.000806    0.527
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 4) Visualize cumulative long{-}short performance}
\NormalTok{ls\_perf }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{cum\_ls =} \FunctionTok{cumprod}\NormalTok{(}\DecValTok{1} \SpecialCharTok{+}\NormalTok{ long\_short) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ cum\_ls)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"purple"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
        \AttributeTok{title =} \StringTok{"Cumulative Long‑Short Momentum Spread"}\NormalTok{,}
        \AttributeTok{x =} \StringTok{"Date"}\NormalTok{,}
        \AttributeTok{y =} \StringTok{"Cumulative Return (Q1‑Q5)"}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Question-3_files/figure-latex/unnamed-chunk-7-1.pdf}}

As shown in the cumulative return plot above, the strategy delivered
strong and consistent outperformance, particularly in the most recent
years. From 2015 to 2025, the long--short spread compounded to nearly
six times, indicating that momentum has been a robust and persistent
signal across the sample period.

Quantitatively, the average monthly return of the strategy was
approximately 0.0842\%, with a median of 0.0806\%. Importantly, the
strategy had a hit rate of 52.7\%, meaning that in over half the months,
the high momentum stocks outperformed their low momentum counterparts.
This edge, though modest monthly, compounds meaningfully over time as
illustrated in the chart above.

Together, these results confirm that the momentum signal successfully
discriminates between winners and losers, and that a simple
quintile-based approach would have added considerable value over the
last decade.

\subsection{Fund's Exposure to
Momentum}\label{funds-exposure-to-momentum}

Lastly, I compared the fund's average momentum rank (based on its
holdings) to that of the broader market. This allowed me to assess
whether the fund has been actively tilting toward high-momentum stocks.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 5) Plot the comparison}
\NormalTok{fund\_vs\_univ }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ date)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ avg\_fund\_rank), }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ avg\_univ\_rank), }\AttributeTok{color =} \StringTok{"grey60"}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
        \AttributeTok{title =} \StringTok{"Average Momentum Rank: Fund vs Universe"}\NormalTok{,}
        \AttributeTok{x =} \StringTok{"Date"}\NormalTok{,}
        \AttributeTok{y =} \StringTok{"Average Rank (lower = stronger momentum)"}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Question-3_files/figure-latex/unnamed-chunk-9-1.pdf}}

As seen in the chart above, the blue line represents the fund's average
momentum rank, while the grey dashed line reflects the average across
the entire market. Over the observed period, the fund consistently
ranked much lower (i.e.~stronger) than the universe.

This tells me that the fund has been systematically tilted toward
high-momentum stocks. In fact, the gap between the fund's average rank
and that of the universe has been wide and stable, suggesting a
deliberate or highly effective selection bias toward momentum.

This pattern supports the idea that the manager has either intentionally
or coincidentally picked up on momentum characteristics in portfolio
construction. This has potentially contributed to improved relative
performance.

\subsection{Conclusion}\label{conclusion}

Looking back over the past decade, my analysis suggests that momentum
has been a meaningful and consistent investment signal in the local
market. The information coefficient shows a generally positive
relationship between momentum ranks and future returns, while the signal
decay analysis confirms that this predictive power persists over the
short term. Additonally, the quintile portfolio results further
reinforce this. The long-short momentum spread has delivered positive
returns, with a hit rate above 50\% and solid average performance.

When comparing my colleague's fund to the broader universe, I found that
the portfolio consistently held stocks with stronger momentum than
average. This suggests that the fund manager has effectively tapped into
momentum exposure, whether by design or indirectly through their
investment style.

All in all, I would conclude that momentum has worked as a signal and
that the fund's performance can be at least partially explained by its
alignment with this factor.

\end{document}
